substitutions:
  type: esp32
  mac: 6be964
  name: Opener Remote 6be964

# ESPHome Core Configuration

esphome:
  name: esphome-${type}-${mac}
  friendly_name: ${name}
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret ha_encryption_key

# Universal Device Configuration

logger:

ota:
  - platform: esphome

binary_sensor:
  - platform: gpio
    name: "Remote CH1"
    pin:
      number: GPIO4
      inverted: true
      mode:
        input: true
        pullup: true
  
  - platform: gpio
    name: "Remote CH2"
    pin:
      number: GPIO5
      inverted: true
      mode:
        input: true
        pullup: true

  - platform: gpio
    name: "Remote CH3"
    pin:
      number: GPIO19
      inverted: true
      mode:
        input: true
        pullup: true