substitutions:
  type: esp32cam
  mac: f184cc
  name: ESPCam 1

# ESPHome Core Configuration

esphome:
  name: esphome-${type}-${mac}
  friendly_name: ${name}
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret ha_encryption_key

# Universal Device Configuration

logger:

ota:

web_server:

# Device Specific Configuration

esp32_camera:
  name: Camera
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600
  jpeg_quality: 10  # max. 63
  max_framerate: 10.0fps
  idle_framerate: 0.2fps
  vertical_flip: true
  horizontal_mirror: false
  brightness: 2 # -2 to 2
  contrast: 1 # -2 to 2
  special_effect: none
  aec_mode: auto
  aec2: false
  ae_level: 0
  aec_value: 300
  agc_mode: auto
  agc_gain_ceiling: 2x
  agc_value: 0
  wb_mode: auto

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

switch:
  - platform: gpio
    name: "Flash"
    pin: GPIO4
    id: flashPin
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 2s
      - switch.turn_off: flashPin