# Your Wi-Fi SSID and password
wifi_ssid: "Bawdy Shop"
wifi_password: "poweroverwhelming"
ha_encryption_key: "s5numZeNRvdt34KGH4+jqEYL34mFt/3DTHalTnTeEco="
ota_password: "poweroverwhelming"
ap_password: "esphomeportallogin"